version: '2'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
      # prevents host/container contamination
      - /usr/src/app/node_modules
    env_file: .env
    environment:
      - NODE_ENV=development
    command: npm run dev
